<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-M4N4JHAP" ignored="0" name="UnHappyScen2" tests="2" failures="1" timestamp="2021-04-04T23:39:11 IST" time="65.682" errors="0">
  <testcase name="Baselogin" time="16.147" classname="Acacemy.UnHappyTests2"/>
  <testcase name="HomePageURL" time="33.963" classname="Acacemy.UnHappyTests2">
    <failure type="java.lang.AssertionError" message="expected [https://reference-test.intellisense.io/#!/id/dashboards/554] but found [https://reference-test.intellisense.io/?product_tour_id=34973#!/id/dashboards/554]">
      <![CDATA[java.lang.AssertionError: expected [https://reference-test.intellisense.io/#!/id/dashboards/554] but found [https://reference-test.intellisense.io/?product_tour_id=34973#!/id/dashboards/554]
at Acacemy.UnHappyTests2.HomePageURL(UnHappyTests2.java:61)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- HomePageURL -->
</testsuite> <!-- UnHappyScen2 -->
